### ISSUE TITLE
[BE] 회원가입 API 구현

### ISSUE THREAD

**Issue by hojun3377** [programmers-kdt-full-stack-3rd/live-chat#1]
## ✍🏻 Description

이메일을 인증하고, 이메일, 비밀번호, 이름과 같은 사용자 정보 DB에 저장

## ✅ To-Do

- [x] POST /api/users/register 엔드포인트 생성
- [ ] 요청 바디의 이메일, 비밀번호, 이름 유효성 검사
- [ ] 이메일 인증 토큰 검사
- [ ] 비밀번호 해싱 처리
- [ ] 사용자 정보 DB에 저장 및 응답
