### ISSUE TITLE
[BE] Socket.io 채팅 기능 구현.

### ISSUE THREAD

**Issue by jjhoooon** [programmers-kdt-full-stack-3rd/live-chat#10]
## ✍🏻 Description

socket.io를 사용해 사용자는 채팅방에서 실시간 채팅을 할 수 있습니다.
이때 메세지 내역은 채팅방에 속해있는 사용자들만 볼 수 있습니다.
이를 위해 Message 테이블을 구성하고, 쿼리문을 작성합니다.

## ✅ To-Do

- [x] socket.io 기능 구현.
- [x] message 테이블 구성.
- [x] message sql query 작성.

## 📨 ETC

필요하다면, 참고할 사항을 적어주세요.
