### ISSUE TITLE
[BE] 인증 번호 생성, 수정, 삭제 API 구현

### ISSUE THREAD

**Issue by hojun3377** [programmers-kdt-full-stack-3rd/live-chat#12]
## ✍🏻 Description

인증 번호를 DB에 생성, 수정, 삭제

## ✅ To-Do

- [x] POST, PUT, DELETE /api/auth/email/verification 엔드포인트 생성
- [x] 요청 이메일, 토큰, 코드 유효성 검사
- [x] PATCH, DELETE 이메일 인증 토큰 검사
- [x] POST, PATCH 랜덤 인증번호(4자리) 생성
- [x] DB에서 리소스 생성, 수정, 삭제
- [x] JWT 토큰 발급 및 응답
