### ISSUE TITLE
[BE] 인증 메일 발송 API 구현

### ISSUE THREAD

**Issue by hojun3377** [programmers-kdt-full-stack-3rd/live-chat#13]
## ✍🏻 Description

사용자의 이메일과 생성된 인증번호를 메일로 발송

## ✅ To-Do

- [ ] POST /api/auth/email/send-verification 엔드포인트 생성
- [ ] 요청 바디의 이메일 주소 유효성 검사
- [ ] 이메일 인증 토큰 검사
- [ ] 인증 번호 복호화
- [ ] Nodemailer로 인증 이메일 발송
- [ ] JWT 토큰 발급 및 응답
