### ISSUE TITLE
[BE] 인증 번호 검사 API 구현

### ISSUE THREAD

**Issue by hojun3377** [programmers-kdt-full-stack-3rd/live-chat#14]
## ✍🏻 Description

클라이언트가 요청한 인증번호를 검사

## ✅ To-Do

- [x] POST /api/auth/email/verify 엔드포인트 생성
- [x] 요청 바디의 인증번호와 이메일 주소 유효성 검사
- [x] 이메일 인증 토큰 검사
- [x] 메일 인증 번호 검사
- [x] JWT 토큰 발급 및 응답
