### ISSUE TITLE
[BE] 인증 메일 발송 API 구현

### ISSUE THREAD

**Issue by hojun3377** [programmers-kdt-full-stack-3rd/live-chat#2]
## ✍🏻 Description

사용자의 이메일과 생성된 인증번호를 메일로 발송

## ✅ To-Do

- [x] POST /api/auth/email/send-verification 엔드포인트 생성
- [x] 요청 바디의 이메일 주소 유효성 검사
- [x] 이메일 인증 토큰 검사
- [x] 인증 번호 DB에서 조회
- [x] Nodemailer로 인증 이메일 발송
- [x] JWT 토큰 발급 및 응답

**Comment by hojun3377** [comment]
DB 설계 다시하고 Task 업데이트 했습니다.

[상세 개발 Task #1. 회원가입 및 로그인](https://github.com/programmers-kdt-full-stack-3rd/live-chat/wiki/Task-Detail-List#1-%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85-%EB%B0%8F-%EB%A1%9C%EA%B7%B8%EC%9D%B8)
