### ISSUE TITLE
[FE] 채팅 화면

### ISSUE THREAD

**Issue by jjhoooon** [programmers-kdt-full-stack-3rd/live-chat#27]
## ✍🏻 Description

- 사용자가 채팅방에 입장하여 메세지를 주고 받는 채팅 화면 페이지를 구현합니다.
- 메세지 컴포넌트(메세지 내용, 시간, 보낸 사람) 작성.

## ✅ To-Do

- [ ] 채팅방 레이아웃 구성
- [ ] 메세지 컴포넌트 작성
- [ ] 보낸 사람 컴포넌트 작성
