### ISSUE TITLE
[BE] 인증 번호 검사 API 구현

### ISSUE THREAD

**Issue by hojun3377** [programmers-kdt-full-stack-3rd/live-chat#3]
## ✍🏻 Description

사용자가 수신한 메일의 인증 번호를 통해 이메일 인증

## ✅ To-Do

- [ ] POST /api/auth/email/verify 엔드포인트 생성
- [ ] 요청 바디의 인증번호와 이메일 주소 유효성 검사
- [ ] 이메일 인증 토큰 검사
- [ ] 메일 인증 번호 검사
- [ ] JWT 토큰 발급 및 응답
